# Generated by Django 3.1.2 on 2020-10-08 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('alternate_phone_number', models.IntegerField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address_line1', models.CharField(max_length=1000)),
                ('address_line2', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('same_billing_address', models.BooleanField(default=True)),
                ('billing_buyer_name', models.CharField(max_length=100)),
                ('billing_phone_number', models.IntegerField()),
                ('billing_email_id', models.EmailField(max_length=100)),
                ('billing_address_line1', models.CharField(max_length=1000)),
                ('billing_address_line2', models.CharField(max_length=1000)),
                ('billing_pincode', models.IntegerField()),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_state', models.CharField(max_length=30)),
                ('billing_country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_channel', models.CharField(blank=True, choices=[('select', 'Select Channel'), ('custom', 'Custom'), ('justgetit', 'JustGetIt')], default='', max_length=10, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jgiship.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=20)),
                ('package_length', models.FloatField()),
                ('package_height', models.FloatField()),
                ('package_sku', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('sku', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('hsn', models.IntegerField()),
                ('product_category', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=10)),
                ('sub_total', models.FloatField()),
                ('shipping_charge', models.FloatField(blank=True, null=True)),
                ('giftwrap_charge', models.FloatField(blank=True, null=True)),
                ('transaction_charge', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgiship.order')),
            ],
        ),
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_nickname', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('address_line1', models.CharField(max_length=1000)),
                ('address_line2', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('is_supplier_address', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('volumetric_weight', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgiship.order')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='package_images/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgiship.packagedetails')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=30)),
                ('eway_bill_number', models.CharField(max_length=30)),
                ('gstin_number', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgiship.order')),
            ],
        ),
    ]
