# Generated by Django 2.2 on 2020-10-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupaddress',
            name='is_supplier_address',
        ),
        migrations.CreateModel(
            name='SelectedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supplier_address', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgiship.PickupAddress')),
            ],
        ),
    ]
