# Generated by Django 2.2 on 2020-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemetrics',
            name='package_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='eway_bill_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='gstin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='reseller_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packagemetrics',
            name='volumetric_weight',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.CharField(max_length=20),
        ),
    ]
