# Generated by Django 3.1.2 on 2020-10-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0002_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
