# Generated by Django 3.1.2 on 2020-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0003_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
