# Generated by Django 2.2 on 2020-10-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0003_auto_20201019_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemetrics',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_metrics_order', to='jgiship.Order'),
        ),
    ]
