# Generated by Django 3.1.2 on 2020-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0004_auto_20201009_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='alternate_phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
