# Generated by Django 2.2 on 2020-10-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0005_auto_20201019_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupaddress', to='jgiship.PickupAddress'),
        ),
    ]
