# Generated by Django 2.0 on 2020-10-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgiship', '0006_auto_20201009_1638'),
        ('jgiship', '0002_auto_20201014_2051'),
    ]

    operations = [
    ]
