STATES = {'andaman and nicobar': 'AN',
          'andhra pradesh': 'AP',
          'arunachal pradesh': 'AR',
          'assam': 'AS',
          'bihar': 'BR',
          'chandigarh': 'CH',
          'dadra and nagar haveli': 'DN',
          'daman and diu': 'DD',
          'delhi': 'DL',
          'goa': 'GA',
          'gujarat': 'GJ',
          'haryana': 'HR',
          'himachal pradesh': 'HP',
          'jammu and kashmir': 'JK',
          'jharkhand': 'JH',
           'karnataka': 'KA',
          'kerala': 'KL',
          'lakshadweep': 'LD',
          'madhya pradesh': 'MP',
          'maharashtra': 'MH',
          'manipur': 'MN',
          'meghalaya': 'ML',
          'mizoram': 'MZ',
          'nagaland': 'NL',
          'odisa': 'OR',
          'pondicherry': 'PY',
          'punjab': 'PB',
          'rajasthan': 'RJ',
          'sikkim': 'SK',
          'tamil nadu': 'TN',
          'telangana': 'TG',
          'tripura': 'TR',
          'uttar pradesh': 'UP',
          'uttarakhand': 'UA',
          'west bengal': 'WB'}
